### ISSUE TITLE
Improve UI of wizard page

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#20] opened 2021-05-21 14:35 UTC
When you have several fields (takes your sample) it's difficult to have an overview of the fields because you have a scrollbar.

![image](https://user-images.githubusercontent.com/1932211/119153473-916eb100-ba51-11eb-841d-55b0bc2b48c5.png)

At first I think we should let the CSS of vscode do the job. For instance the stub.html include bootstrap.css which grow up the size of the policy. Here a quickresult (we should fix the line problem which takes too many place)

![image](https://user-images.githubusercontent.com/1932211/119154212-3c7f6a80-ba52-11eb-8698-9f787fbdb90a.png)

A second improvement that we could dois to align label, input text and error message in the same line:

Here a quick result (didwith mspaint)

![image](https://user-images.githubusercontent.com/1932211/119154567-908a4f00-ba52-11eb-83f7-155554b529bb.png)

**Comment by robstryker** [comment] 2021-05-21 20:25
I know you were using older UI version here. If you still have a criticism, mind suggesting a patch? Or if the issue is no longer valid, closing it is good too :D

**Comment by angelozerr** [comment] 2021-05-22 10:08
Let me compare with existing vscode styles (like Release notes to compare it with vscode-wizard UI)

**Comment by angelozerr** [comment] 2021-05-22 11:45
Here my first feedbacks:

 * checkbox have not the same look than vscode
 * character size is 14px although vscode is 13px

![image](https://user-images.githubusercontent.com/1932211/119225402-e79c2c80-bb03-11eb-9273-546c71793850.png)

**Comment by robstryker** [comment] 2021-05-26 21:00
I fixed the font size, not the checkbox.

**Closed as completed** 2021-05-26 20:59 UTC
